---
kind: pipeline
name: ci

steps:
- name: perform_tests
  image: registry.nalewajski.pl/node-dubnium-chrome
  commands:
  - npm install -g npm@latest
  - npm install -g ember-cli
  - npm install
  - cp config/environment.js.sample config/environment.js
  - npm run lint:hbs
  - npm run lint:js
  - npm test ci

---
kind: pipeline
name: cd

clone:
  disable: true

steps:
- name: update_docker
  image: docker:git
  environment:
    POMPA_DOCKER_DEPLOY_KEY:
      from_secret: pompa_docker_deploy_key
  commands:
  - export SHORT_COMMIT="$(echo $DRONE_COMMIT | cut -c1-7)"
  - mkdir -p ~/.ssh
  - echo -ne "$POMPA_DOCKER_DEPLOY_KEY" > ~/.ssh/id_rsa
  - ssh-keyscan -H github.com > ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/id_rsa ~/.ssh/known_hosts
  - git clone git@github.com:m1nl/pompa-docker.git
  - cd pompa-docker
  - git config user.email "drone@nalewajski.pl"
  - git config user.name "Drone CI"
  - git submodule init -- web/pompa
  - git submodule update --checkout -- web/pompa
  - cd web/pompa
  - git checkout $DRONE_COMMIT
  - cd ../..
  - git add web/pompa
  - git commit --allow-empty -m "update pompa with $SHORT_COMMIT ($DRONE_COMMIT_MESSAGE) by $DRONE_COMMIT_AUTHOR"
  - git push origin master

trigger:
  status:
  - success
  branch:
  - master
  event:
  - push

depends_on:
- ci
